# -*- coding: utf-8 -*-
"""openstreetmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHI4sZvVwohmaSS4JlLeg7us95dA1u6T
"""

pip install osmnx folium geopandas

import osmnx as ox
import folium

# Define a location (e.g., a city or neighborhood)
place_name = "Kharar, Punjab, India"

# Download the street network for the specified place from OpenStreetMap
graph = ox.graph_from_place(place_name, network_type='drive')

# Convert the graph to GeoDataFrames
nodes, edges = ox.graph_to_gdfs(graph)

# Create a map centered around the location
m = folium.Map(location=[edges['geometry'].centroid.y.mean(), edges['geometry'].centroid.x.mean()], zoom_start=12)

# Add edges (streets) to the map
for _, row in edges.iterrows():
    points = [(point[1], point[0]) for point in row['geometry'].coords]
    folium.PolyLine(points, color="blue", weight=2.5).add_to(m)

# Save map as an HTML file
m.save("kharar.html")

# Display the map (optional for Jupyter environments)
m